// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Url           string
	UserID        uuid.UUID
	LastFetchedAt sql.NullTime
}

type Post struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       sql.NullString
	Link        sql.NullString
	Description sql.NullString
	Author      sql.NullString
	Category    sql.NullString
	Comments    sql.NullString
	Enclosure   []string
	Guid        sql.NullString
	Pubdate     sql.NullString
	Source      sql.NullString
	FeedID      uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ApiKey    string
}
